[shell]
font_family = "Lexend"
setup_wizard_enabled = false
polkit_agent = true
password_style = "random"
settings_show_advanced = true
launch_apps_as_systemd_services = true
screen_time_enabled = true

[shell.shadow]
direction = "center"
alpha = 0.25

# TODO: Screenshot management
