[shell]
font_family = "Lexend"
setup_wizard_enabled = false
polkit_agent = true
settings_show_advanced = true
launch_apps_as_systemd_services = true
screen_time_enabled = true

[shell.shadow]
direction = "center"
alpha = 0.25

[shell.panel]
launcher_placement = "attached"
clipboard_placement = "attached"
control_center_placement = "attached"
wallpaper_placement = "attached"
session_placement = "attached"
polkit_placement = "attached"

[shell.launcher.dmenu.entry.ssh]
label = "SSH"
command = "grep -P '^Host ([^*]+)$' $HOME/.ssh/config | sed 's/Host //'"
exec = "wezterm ssh {selection}"
prefix = "/ssh"
glyph = "server"

[shell.launcher.dmenu.entry.ser]
label = "Services"
command = "systemctl --user list-units --type=service --no-legend --all | sed -e 's/^[[:space:]●○*]*//' -e 's/[[:space:]].*//' | grep -v -E '@'"
exec = "wezterm -e systemctl --user status -n 400  \"{selection}\""
prefix = "/ser"
glyph = "terminal"

[shell.launcher.dmenu.entry.apps]
label = "Apps"
command = "systemctl --user list-units --type=service --no-legend --all | sed -e 's/^[[:space:]●○*]*//' -e 's/[[:space:]].*//' | grep 'app-'"
exec = "wezterm -e systemctl --user status -n 400 \"{selection}\""
prefix = "/app"
glyph = "terminal"
