directory: ~/Media/Music
library: ~/.sync/musiclibrary.db

import:
    move: yes

plugins:
  - musicbrainz
  - scrub
  - fetchart
  - embedart
  - thumbnails
  - lastgenre

fetchart:
    enforce_ratio: yes
    store_source: yes
