[bar]
order = ["main"]

[bar.main]
position = "top"
thickness = 40
margin_ends = 0
margin_edge = 0
padding = 16
widget_spacing = 24

panel_overlap = 0
background_opacity = 1

radius = 0
radius_bottom_left = 19
radius_bottom_right = 19
concave_edge_corners = true

capsule_thickness = 0.65
capsule_padding = 6
capsule_border = "outline"
start = ["control-center", "group:left", "clock", "notifications"]
center = ["cpu", "spacer", "ram", "workspaces", "gpu", "spacer", "vram"]
end = ["tray", "audio_visualizer", "group:right", "session"]

[[bar.main.capsule_group]]
id = "left"
members = ["network", "bluetooth", "privacy"]
padding = 12
thickness = 0.6
border = "on_primary"

[[bar.main.capsule_group]]
id = "right"
members = ["keyboard_layout", "volume", "battery"]
thickness = 0.6
padding = 12
border = "on_primary"
