[widget.control-center]
custom_image = "/usr/share/noctalia/assets/images/distros/fedora.svg"
custom_image_colorize = false

[widget.network]
show_label = true

[widget.bluetooth]
show_label = true

[widget.sysmon]
label_min_width = 32

[widget.workspaces]
active_pill_size = 3.8
inactive_pill_size = 2.6
capsule = true

[widget.media]
min_length = 200
max_length = 200

[widget.audio_visualizer]
width = 142
bands = 12
show_when_idle = true
color_1 = "primary"
color_2 = "secondary"

[widget.clock]
format = "{:%H:%M}  •  {:%d.%m.%Y}"
