[widget.control-center]
custom_image = "/usr/share/noctalia/assets/images/distros/fedora.svg"
custom_image_colorize = false

[widget.workspaces]
active_pill_size = 3.8
inactive_pill_size = 2.6
capsule = true

[widget.clock]
format = "{:%H:%M}  •  {:%d.%m.%Y}"
